---
- hosts: all
  gather_facts: no
  tasks:
    - include_tasks:
        file: ensure_python.yaml

- hosts: web
  vars_files: ../var/environment.yaml
  tasks:
    - name: Set up environment variables
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^export {{ item }}='
        owner: root
        group: root
        mode: '0644'
        line: export {{ item }}={{ lookup('ansible.builtin.env', item) }}
      loop: "{{ env_var }}"

- hosts: web
  vars_files: ../var/setup.yaml
  tasks:
    - ansible.builtin.include_tasks: setup_web_for_mw.yaml
  handlers:
    - name: Reload Apache
      become: yes
      ansible.builtin.service:
        name: apache2
        state: reloaded

- hosts: web
  vars_files: ../var/setup.yaml
  roles:
    - role: geerlingguy.composer
      become: yes
  tasks:
    - ansible.builtin.include_tasks: setup_mw.yaml
