---
- hosts: all
  gather_facts: no
  tasks:
    - include_tasks:
        file: ensure_python.yaml

- hosts: web
  vars_files: ../var/environment.yaml
  tasks:
    - name: Set up environment variables
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^export {{ item }}='
        owner: root
        group: root
        mode: '0644'
        line: export {{ item }}={{ lookup('ansible.builtin.env', item) }}
      loop: "{{ env_var }}"

- hosts: web
  vars_files: ../var/sw-setup.yaml
  tasks:
    - name: Set up apache+php
      become: yes
      ansible.builtin.apt:
        pkg: "{{ debian_wiki_packages }}"

    - name: Make sure environment is copied in for php scripts
      become: yes
      ansible.builtin.copy:
        src: ../files/envvars.ini
        dest: "{{ item }}"
      loop:
          - /etc/php/7.4/cli/conf.d/99-envvars.ini
          - /etc/php/7.4/apache2/conf.d/99-envvars.ini

    - name: Source /etc/environment for apache
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/apache2/envvars
        regexp: '^\. /etc/environment'
        line: . /etc/environment

    - name: Check out mediawiki
      ansible.builtin.git:
        accept_newhostkey: y
        dest: /var/www/wikiapiary/public_html/w
        repo: https://gerrit.wikimedia.org/r/mediawiki/core.git
        single_branch: y
        version: REL1_39
        depth: 1

